export const FALLBACK_CATEGORIES = [
  { _id: 'cat_1', name: 'Electrical Repairs & Wiring', slug: 'electrician', icon: '⚡', basePrice: 299, description: 'Complete electrical troubleshooting, circuit breaker replacement, wiring repairs, and installations.' },
  { _id: 'cat_2', name: 'AC Servicing & Deep Repair', slug: 'ac-repair', icon: '❄️', basePrice: 549, description: 'Jet pump foam wash, gas leak inspection & recharge, PCB troubleshooting, and maintenance.' },
  { _id: 'cat_3', name: 'Plumbing & Pipe Solutions', slug: 'plumber', icon: '🔧', basePrice: 349, description: 'Emergency leak detection, tap & mixer fitting, drain unblocking, water heater setup, and more.' },
  { _id: 'cat_4', name: 'Full Home Deep Cleaning', slug: 'cleaning', icon: '✨', basePrice: 1299, description: 'Intensive hospital-grade sanitization for kitchens, bathrooms, floors, and upholstery.' },
  { _id: 'cat_5', name: 'Carpentry & Woodwork Assembly', slug: 'carpenter', icon: '🪚', basePrice: 449, description: 'Custom cabinetry repairs, door/lock fixing, hinges, modular furniture setup, and precision work.' },
  { _id: 'cat_6', name: 'Interior & Exterior Painting', slug: 'painter', icon: '🎨', basePrice: 1499, description: 'Waterproofing, wall crack treatment, texture painting, and premium emulsion finishes.' },
  { _id: 'cat_7', name: 'Organic Pest Control', slug: 'pest-control', icon: '🛡️', basePrice: 749, description: 'Odorless gel & herbal spray treatment for cockroaches, termites, bedbugs, and rodents.' },
  { _id: 'cat_8', name: 'Smart Home & CCTV Setup', slug: 'smart-home', icon: '📡', basePrice: 899, description: 'Smart switch configuration, IP camera and video doorbell installations, WiFi mesh, and more.' },
];

export const FALLBACK_PROS = [
  {
    _id: 'pro_1',
    businessName: 'Apex Electricals & Power Systems',
    tagline: 'Licensed Master Electrician • 9+ Years Experience',
    description: 'Specializing in residential wiring, short-circuit troubleshooting, circuit breaker upgrades, inverter setup, and emergency power restoration across Salt Lake and New Town.',
    experienceYears: 9,
    rating: 4.9,
    totalReviews: 92,
    completedJobs: 92,
    responseRate: 99,
    trustScore: 95,
    trustTier: 'Elite Pro',
    verificationStatus: 'VERIFIED',
    skills: ['Electrician', 'Inverter Setup', 'Short Circuit', 'Earthing', 'Home Automation'],
    location: { city: 'Kolkata', address: 'Salt Lake Sector V, Kolkata', coordinates: [88.4312, 22.5769] },
    services: [
      { name: 'Electrical Diagnostics & Wiring Fault Rectification', slug: 'electrician', price: 299, priceType: 'starts_at', description: 'Complete circuit inspection with safety testing.' },
      { name: 'Inverter & Battery Wiring Installation', slug: 'electrician', price: 699, priceType: 'fixed', description: 'Full inverter bypass switch installation and heavy gauge connection.' },
      { name: 'Sub-meter & MCB Distribution Box Replacement', slug: 'electrician', price: 499, priceType: 'fixed', description: 'Safe replacement of burned circuit breakers.' },
    ],
    userId: { avatar: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?auto=format&fit=crop&w=200&q=80' },
  },
  {
    _id: 'pro_2',
    businessName: 'Metro Air Conditioning & Cooling',
    tagline: 'High-Pressure Jet Pump Foam Servicing & Gas Charging',
    description: 'Over 8 years servicing split and window ACs across Kolkata, Park Street, and Ballygunge. 100% genuine copper coils and refrigerant gas guarantee.',
    experienceYears: 8,
    rating: 4.8,
    totalReviews: 78,
    completedJobs: 78,
    responseRate: 97,
    trustScore: 92,
    trustTier: 'Elite Pro',
    verificationStatus: 'VERIFIED',
    skills: ['AC Repair', 'Jet Foam Cleaning', 'Gas Leak Fix', 'Split AC Installation'],
    location: { city: 'Kolkata', address: 'Park Street, Kolkata', coordinates: [88.3512, 22.5513] },
    services: [
      { name: 'Jet Pump Deep Foam AC Cleaning', slug: 'ac-repair', price: 549, priceType: 'fixed', description: 'Anti-bacterial jet wash for blower, cooling fins, and drain pipe.' },
      { name: 'R32 / R410A Pure Refrigerant Gas Top-Up', slug: 'ac-repair', price: 1799, priceType: 'fixed', description: 'Nitrogen pressure leak test and optimal cooling top up.' },
    ],
    userId: { avatar: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?auto=format&fit=crop&w=200&q=80' },
  },
  {
    _id: 'pro_3',
    businessName: 'Prime Plumbing & Leak Solutions',
    tagline: 'Master Plumber • Drain Clog & Water Heater Specialist',
    description: 'Reliable plumbing services across South and Central Kolkata: Ballygunge, Gariahat, and Jadavpur. Sanitary fittings, overhead tank floats, and motorized drain unblocking.',
    experienceYears: 11,
    rating: 4.9,
    totalReviews: 110,
    completedJobs: 110,
    responseRate: 98,
    trustScore: 96,
    trustTier: 'Elite Pro',
    verificationStatus: 'VERIFIED',
    skills: ['Plumbing', 'Drain Cleaning', 'Tap Mixer', 'Water Tank Float', 'Geyser Fitting'],
    location: { city: 'Kolkata', address: 'Ballygunge, Kolkata', coordinates: [88.3653, 22.5280] },
    services: [
      { name: 'Concealed Pipe Leakage Detection & Repair', slug: 'plumber', price: 349, priceType: 'starts_at', description: 'Instant detection and repair with quality PVC/CPVC.' },
      { name: 'Motorized High-Torque Drain Unblocking', slug: 'plumber', price: 599, priceType: 'fixed', description: 'Heavy duty steel snake clearing bathroom and kitchen lines.' },
    ],
    userId: { avatar: 'https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?auto=format&fit=crop&w=200&q=80' },
  },
  {
    _id: 'pro_4',
    businessName: 'PureSpark Deep Cleaning & Sanitization',
    tagline: 'Eco-Friendly Hospital Grade Home Sanitization',
    description: 'Intensive deep cleaning solutions for apartments, villas, and commercial offices in New Town and Salt Lake. Single-disc floor buffing and non-toxic sanitizers.',
    experienceYears: 6,
    rating: 4.9,
    totalReviews: 65,
    completedJobs: 65,
    responseRate: 96,
    trustScore: 90,
    trustTier: 'Elite Pro',
    verificationStatus: 'VERIFIED',
    skills: ['Deep Cleaning', 'Sanitization', 'Kitchen Degreasing', 'Bathroom Descaling'],
    location: { city: 'Kolkata', address: 'New Town Action Area 1, Kolkata', coordinates: [88.4682, 22.5855] },
    services: [
      { name: 'Complete 2BHK Intensive Deep Sanitization', slug: 'cleaning', price: 2199, priceType: 'fixed', description: 'Full house scrubbing, window buffing, and chemical-free floor wash.' },
      { name: 'Intense Bathroom Acid-Free Descaling', slug: 'cleaning', price: 599, priceType: 'fixed', description: 'Tile grout restoration, mirror shine, and fixture polishing.' },
    ],
    userId: { avatar: 'https://images.unsplash.com/photo-1544005313-94ddf0286df2?auto=format&fit=crop&w=200&q=80' },
  },
  {
    _id: 'pro_5',
    businessName: 'Urban Woodcraft & Carpentry Studio',
    tagline: 'Precision Woodworking & Modular Furniture Setup',
    description: 'Expert carpentry for IKEA and modular furniture assembly, wardrobe sliding channels, custom cabinet repair, and hydraulic hinge fitting.',
    experienceYears: 10,
    rating: 4.8,
    totalReviews: 82,
    completedJobs: 82,
    responseRate: 95,
    trustScore: 89,
    trustTier: 'Verified Master',
    verificationStatus: 'VERIFIED',
    skills: ['Carpentry', 'Modular Furniture', 'Hinges', 'Door Locks', 'Cabinet Repair'],
    location: { city: 'Kolkata', address: 'Alipore, Kolkata', coordinates: [88.3312, 22.5312] },
    services: [
      { name: 'Door Lock / Deadbolt Installation', slug: 'carpenter', price: 349, priceType: 'starts_at', description: 'Mortise lock, latch, and safety handle fitting.' },
      { name: 'Modular Furniture & Bed Frame Assembly', slug: 'carpenter', price: 599, priceType: 'starts_at', description: 'Precision alignment for engineered wood sets.' },
    ],
    userId: { avatar: 'https://images.unsplash.com/photo-1506794778202-cad84cf45f1d?auto=format&fit=crop&w=200&q=80' },
  },
  {
    _id: 'pro_6',
    businessName: 'ShieldGuard Organic Pest Control',
    tagline: 'Odorless Herbal Spray & German Gel Technology',
    description: 'Child-safe and pet-safe pest eradication for termites, cockroaches, bedbugs, and rodents with a 90-day re-service warranty.',
    experienceYears: 7,
    rating: 4.9,
    totalReviews: 58,
    completedJobs: 58,
    responseRate: 98,
    trustScore: 91,
    trustTier: 'Elite Pro',
    verificationStatus: 'VERIFIED',
    skills: ['Pest Control', 'Termite Eradication', 'Cockroach Gel', 'Bedbug Heat Treatment'],
    location: { city: 'Kolkata', address: 'Salt Lake City, Kolkata', coordinates: [88.4112, 22.5812] },
    services: [
      { name: 'Odorless Cockroach Herbal Gel Treatment (2 BHK)', slug: 'pest-control', price: 749, priceType: 'fixed', description: 'Long-lasting Bayer gel application behind hinges and drains.' },
      { name: 'Complete Anti-Termite Drill & Injection Warranty', slug: 'pest-control', price: 1899, priceType: 'starts_at', description: 'Wall and woodwork chemical barrier installation.' },
    ],
    userId: { avatar: 'https://images.unsplash.com/photo-1522075469751-3a6694fb2f61?auto=format&fit=crop&w=200&q=80' },
  },
  {
    _id: 'pro_7',
    businessName: 'Apex Smart Home & CCTV Automation',
    tagline: 'IP Security Cameras • Smart Switches • WiFi Mesh',
    description: 'Complete home automation, smart touch panel installation, video doorbells, and high-definition NVR surveillance setups.',
    experienceYears: 5,
    rating: 4.8,
    totalReviews: 44,
    completedJobs: 44,
    responseRate: 94,
    trustScore: 88,
    trustTier: 'Verified Master',
    verificationStatus: 'VERIFIED',
    skills: ['Smart Home', 'CCTV Setup', 'Video Doorbell', 'WiFi Mesh'],
    location: { city: 'Kolkata', address: 'Rajarhat, Kolkata', coordinates: [88.4712, 22.6212] },
    services: [
      { name: 'Smart Switchboard & App Automation (per room)', slug: 'smart-home', price: 899, priceType: 'starts_at', description: 'Integration of smart modules with existing switchboards.' },
      { name: '4-Camera HD Night-Vision CCTV Setup & Cabling', slug: 'smart-home', price: 2499, priceType: 'fixed', description: 'Camera mounting, DVR configuration, and mobile app streaming.' },
    ],
    userId: { avatar: 'https://images.unsplash.com/photo-1519085360753-af0119f7cbe7?auto=format&fit=crop&w=200&q=80' },
  },
];
