export const FALLBACK_CATEGORIES = [
  { _id: 'cat_1', name: 'Electrical Repairs & Wiring', slug: 'electrician', icon: '⚡', basePrice: 299, description: 'Complete electrical troubleshooting, circuit breaker replacement, wiring repairs, and installations.' },
  { _id: 'cat_2', name: 'AC Servicing & Deep Repair', slug: 'ac-repair', icon: '❄️', basePrice: 549, description: 'Jet pump foam wash, gas leak inspection & recharge, PCB troubleshooting, and maintenance.' },
  { _id: 'cat_3', name: 'Plumbing & Pipe Solutions', slug: 'plumber', icon: '🔧', basePrice: 349, description: 'Emergency leak detection, tap & mixer fitting, drain unblocking, water heater setup, and more.' },
  { _id: 'cat_4', name: 'Full Home Deep Cleaning', slug: 'cleaning', icon: '✨', basePrice: 1299, description: 'Intensive hospital-grade sanitization for kitchens, bathrooms, floors, and upholstery.' },
  { _id: 'cat_5', name: 'Carpentry & Woodwork Assembly', slug: 'carpenter', icon: '🪚', basePrice: 449, description: 'Custom cabinetry repairs, door/lock fixing, hinges, modular furniture setup, and precision work.' },
  { _id: 'cat_6', name: 'Interior & Exterior Painting', slug: 'painter', icon: '🎨', basePrice: 1499, description: 'Waterproofing, wall crack treatment, texture painting, and premium emulsion finishes.' },
  { _id: 'cat_7', name: 'Organic Pest Control', slug: 'pest-control', icon: '🛡️', basePrice: 749, description: 'Odorless gel & herbal spray treatment for cockroaches, termites, bedbugs, and rodents.' },
  { _id: 'cat_8', name: 'Smart Home & CCTV Setup', slug: 'smart-home', icon: '📡', basePrice: 899, description: 'Smart switch configuration, IP camera and video doorbell installations, WiFi mesh, and more.' },
];

export const FALLBACK_PROS = [
  // 1. ELECTRICIANS (2 Specialists)
  {
    _id: 'pro_elec_1',
    businessName: 'Apex Electricals & Power Systems',
    category: 'electrician',
    tagline: 'Licensed Master Electrician • 9+ Years Experience',
    description: 'Specializing in residential wiring, short-circuit troubleshooting, circuit breaker upgrades, inverter setup, and emergency power restoration across Salt Lake and New Town.',
    experienceYears: 9,
    rating: 4.9,
    totalReviews: 92,
    completedJobs: 92,
    responseRate: 99,
    trustScore: 95,
    trustTier: 'Elite Pro',
    verificationStatus: 'VERIFIED',
    availabilityType: 'booked_until_nov',
    leadTimeNotice: 'Booked through September & October. Earliest open booking starts November 2026.',
    alternativeProId: 'pro_elec_2',
    skills: ['Electrician', 'Inverter Setup', 'Short Circuit', 'Earthing', 'Home Automation'],
    location: { city: 'Kolkata', address: 'Salt Lake Sector V, Kolkata', coordinates: [88.4312, 22.5769] },
    services: [
      { name: 'Electrical Diagnostics & Wiring Fault Rectification', slug: 'electrician', price: 299, priceType: 'starts_at', description: 'Complete circuit inspection with safety testing.' },
      { name: 'Inverter & Battery Wiring Installation', slug: 'electrician', price: 699, priceType: 'fixed', description: 'Full inverter bypass switch installation and heavy gauge connection.' },
    ],
    userId: { avatar: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?auto=format&fit=crop&w=200&q=80' },
  },
  {
    _id: 'pro_elec_2',
    businessName: 'VoltMaster Quick Response Electricians',
    category: 'electrician',
    tagline: 'Emergency Dispatch Electrician • Open Slots Tomorrow',
    description: 'Fast-response electrician service for immediate switchboard replacement, fan regulator repairs, LED track lighting, and household power faults.',
    experienceYears: 6,
    rating: 4.8,
    totalReviews: 64,
    completedJobs: 64,
    responseRate: 97,
    trustScore: 89,
    trustTier: 'Verified Master',
    verificationStatus: 'VERIFIED',
    availabilityType: 'available_now',
    leadTimeNotice: 'Available Tomorrow with open morning and afternoon slots!',
    alternativeProId: 'pro_elec_1',
    skills: ['Electrician', 'Emergency Repairs', 'Switchboard Setup', 'Light Fitting'],
    location: { city: 'Kolkata', address: 'Park Circus, Kolkata', coordinates: [88.3698, 22.5448] },
    services: [
      { name: 'Rapid Power Fault & Switchboard Fix', slug: 'electrician', price: 249, priceType: 'starts_at', description: 'Fast diagnostics and replacement of sockets and switches.' },
      { name: 'Ceiling Fan & Chandelier Fitting', slug: 'electrician', price: 349, priceType: 'fixed', description: 'Secure ceiling anchor mounting with dynamic balance check.' },
    ],
    userId: { avatar: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?auto=format&fit=crop&w=200&q=80' },
  },

  // 2. AC REPAIR (2 Specialists)
  {
    _id: 'pro_ac_1',
    businessName: 'Metro Air Conditioning & Cooling',
    category: 'ac-repair',
    tagline: 'High-Pressure Jet Pump Foam Servicing & Gas Charging',
    description: 'Over 8 years servicing split and window ACs across Kolkata, Park Street, and Ballygunge. 100% genuine copper coils and refrigerant gas guarantee.',
    experienceYears: 8,
    rating: 4.8,
    totalReviews: 78,
    completedJobs: 78,
    responseRate: 97,
    trustScore: 92,
    trustTier: 'Elite Pro',
    verificationStatus: 'VERIFIED',
    availabilityType: 'booked_until_nov',
    leadTimeNotice: 'Booked through September & October. Earliest open booking starts November 2026.',
    alternativeProId: 'pro_ac_2',
    skills: ['AC Repair', 'Jet Foam Cleaning', 'Gas Leak Fix', 'Split AC Installation'],
    location: { city: 'Kolkata', address: 'Park Street, Kolkata', coordinates: [88.3512, 22.5513] },
    services: [
      { name: 'Jet Pump Deep Foam AC Cleaning', slug: 'ac-repair', price: 549, priceType: 'fixed', description: 'Anti-bacterial jet wash for blower, cooling fins, and drain pipe.' },
      { name: 'R32 / R410A Pure Refrigerant Gas Top-Up', slug: 'ac-repair', price: 1799, priceType: 'fixed', description: 'Nitrogen pressure leak test and optimal cooling top up.' },
    ],
    userId: { avatar: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?auto=format&fit=crop&w=200&q=80' },
  },
  {
    _id: 'pro_ac_2',
    businessName: 'CoolBreeze Express AC Techs',
    category: 'ac-repair',
    tagline: 'Next-Day AC Service & Emergency Cooling Support',
    description: 'Quick cooling diagnostics, capacitor replacements, drain pipe water-leak repairs, and seasonal AC servicing in Salt Lake and New Town.',
    experienceYears: 5,
    rating: 4.7,
    totalReviews: 52,
    completedJobs: 52,
    responseRate: 95,
    trustScore: 87,
    trustTier: 'Verified Master',
    verificationStatus: 'VERIFIED',
    availabilityType: 'available_now',
    leadTimeNotice: 'Available Tomorrow with open slots!',
    alternativeProId: 'pro_ac_1',
    skills: ['AC Repair', 'Water Leakage', 'Capacitor Change', 'Filter Cleaning'],
    location: { city: 'Kolkata', address: 'New Town Action Area 2, Kolkata', coordinates: [88.4812, 22.5955] },
    services: [
      { name: 'AC Drain Leakage & Water Drip Fix', slug: 'ac-repair', price: 399, priceType: 'fixed', description: 'Unclog drain lines and seal indoor tray joints.' },
      { name: 'Comprehensive Split AC General Service', slug: 'ac-repair', price: 499, priceType: 'fixed', description: 'Filter cleaning, coil washing, and amperage testing.' },
    ],
    userId: { avatar: 'https://images.unsplash.com/photo-1506794778202-cad84cf45f1d?auto=format&fit=crop&w=200&q=80' },
  },

  // 3. PLUMBERS (2 Specialists)
  {
    _id: 'pro_plumb_1',
    businessName: 'Prime Plumbing & Leak Solutions',
    category: 'plumber',
    tagline: 'Master Plumber • Drain Clog & Water Heater Specialist',
    description: 'Reliable plumbing services across South and Central Kolkata: Ballygunge, Gariahat, and Jadavpur. Sanitary fittings, overhead tank floats, and motorized drain unblocking.',
    experienceYears: 11,
    rating: 4.9,
    totalReviews: 110,
    completedJobs: 110,
    responseRate: 98,
    trustScore: 96,
    trustTier: 'Elite Pro',
    verificationStatus: 'VERIFIED',
    availabilityType: 'booked_until_nov',
    leadTimeNotice: 'Booked through September & October. Earliest open booking starts November 2026.',
    alternativeProId: 'pro_plumb_2',
    skills: ['Plumbing', 'Drain Cleaning', 'Tap Mixer', 'Water Tank Float', 'Geyser Fitting'],
    location: { city: 'Kolkata', address: 'Ballygunge, Kolkata', coordinates: [88.3653, 22.5280] },
    services: [
      { name: 'Concealed Pipe Leakage Detection & Repair', slug: 'plumber', price: 349, priceType: 'starts_at', description: 'Instant detection and repair with quality PVC/CPVC.' },
      { name: 'Motorized High-Torque Drain Unblocking', slug: 'plumber', price: 599, priceType: 'fixed', description: 'Heavy duty steel snake clearing bathroom and kitchen lines.' },
    ],
    userId: { avatar: 'https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?auto=format&fit=crop&w=200&q=80' },
  },
  {
    _id: 'pro_plumb_2',
    businessName: 'HydroFix Emergency Rapid Plumbers',
    category: 'plumber',
    tagline: 'Urgent Leak Fix & Pipe Fitting • Slots Open Tomorrow',
    description: 'Fast and responsive plumbing team handling pipe burst emergencies, bathroom fixture fittings, flush valve repairs, and water pump servicing.',
    experienceYears: 7,
    rating: 4.8,
    totalReviews: 73,
    completedJobs: 73,
    responseRate: 99,
    trustScore: 90,
    trustTier: 'Elite Pro',
    verificationStatus: 'VERIFIED',
    availabilityType: 'available_now',
    leadTimeNotice: 'Available Tomorrow with open slots!',
    alternativeProId: 'pro_plumb_1',
    skills: ['Plumbing', 'Emergency Leak Fix', 'Tap Replacement', 'Flush Tank'],
    location: { city: 'Kolkata', address: 'Gariahat, Kolkata', coordinates: [88.3688, 22.5180] },
    services: [
      { name: 'Emergency Tap & Sink Leak Rectification', slug: 'plumber', price: 299, priceType: 'starts_at', description: 'Immediate washer and cartridge replacement.' },
      { name: 'Flush Tank & Commode Syphon Overhaul', slug: 'plumber', price: 449, priceType: 'fixed', description: 'Replacement of internal ball valve and inlet tube.' },
    ],
    userId: { avatar: 'https://images.unsplash.com/photo-1519085360753-af0119f7cbe7?auto=format&fit=crop&w=200&q=80' },
  },

  // 4. CLEANING (2 Specialists)
  {
    _id: 'pro_clean_1',
    businessName: 'PureSpark Deep Cleaning & Sanitization',
    category: 'cleaning',
    tagline: 'Eco-Friendly Hospital Grade Home Sanitization',
    description: 'Intensive deep cleaning solutions for apartments, villas, and commercial offices in New Town and Salt Lake. Single-disc floor buffing and non-toxic sanitizers.',
    experienceYears: 6,
    rating: 4.9,
    totalReviews: 65,
    completedJobs: 65,
    responseRate: 96,
    trustScore: 90,
    trustTier: 'Elite Pro',
    verificationStatus: 'VERIFIED',
    availabilityType: 'booked_until_nov',
    leadTimeNotice: 'Booked through September & October. Earliest open booking starts November 2026.',
    alternativeProId: 'pro_clean_2',
    skills: ['Deep Cleaning', 'Sanitization', 'Kitchen Degreasing', 'Bathroom Descaling'],
    location: { city: 'Kolkata', address: 'New Town Action Area 1, Kolkata', coordinates: [88.4682, 22.5855] },
    services: [
      { name: 'Complete 2BHK Intensive Deep Sanitization', slug: 'cleaning', price: 2199, priceType: 'fixed', description: 'Full house scrubbing, window buffing, and chemical-free floor wash.' },
      { name: 'Intense Bathroom Acid-Free Descaling', slug: 'cleaning', price: 599, priceType: 'fixed', description: 'Tile grout restoration, mirror shine, and fixture polishing.' },
    ],
    userId: { avatar: 'https://images.unsplash.com/photo-1544005313-94ddf0286df2?auto=format&fit=crop&w=200&q=80' },
  },
  {
    _id: 'pro_clean_2',
    businessName: 'CrystalClean Pro Home Services',
    category: 'cleaning',
    tagline: 'Express Kitchen & Sofa Shampooing • Available This Week',
    description: 'Reliable cleaning crew specializing in fabric sofa vacuuming and extraction, chimney degreasing, and balcony pressure washing.',
    experienceYears: 4,
    rating: 4.8,
    totalReviews: 48,
    completedJobs: 48,
    responseRate: 94,
    trustScore: 86,
    trustTier: 'Verified Master',
    verificationStatus: 'VERIFIED',
    availabilityType: 'available_now',
    leadTimeNotice: 'Available Tomorrow with open slots!',
    alternativeProId: 'pro_clean_1',
    skills: ['Cleaning', 'Sofa Shampooing', 'Chimney Degreasing', 'Floor Polishing'],
    location: { city: 'Kolkata', address: 'Bhowanipore, Kolkata', coordinates: [88.3475, 22.5310] },
    services: [
      { name: 'Sofa 3-Seater Wet Extraction & Sanitizing', slug: 'cleaning', price: 899, priceType: 'fixed', description: 'High-suction foam extraction removing deep dust mites.' },
      { name: 'Kitchen Exhaust & Degreasing Wash', slug: 'cleaning', price: 699, priceType: 'fixed', description: 'Heavy grease dissolving for tiles, slabs, and cabinets.' },
    ],
    userId: { avatar: 'https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?auto=format&fit=crop&w=200&q=80' },
  },

  // 5. CARPENTRY (2 Specialists)
  {
    _id: 'pro_carp_1',
    businessName: 'Urban Woodcraft & Carpentry Studio',
    category: 'carpenter',
    tagline: 'Precision Woodworking & Modular Furniture Setup',
    description: 'Expert carpentry for IKEA and modular furniture assembly, wardrobe sliding channels, custom cabinet repair, and hydraulic hinge fitting.',
    experienceYears: 10,
    rating: 4.8,
    totalReviews: 82,
    completedJobs: 82,
    responseRate: 95,
    trustScore: 89,
    trustTier: 'Verified Master',
    verificationStatus: 'VERIFIED',
    availabilityType: 'booked_until_nov',
    leadTimeNotice: 'Booked through September & October. Earliest open booking starts November 2026.',
    alternativeProId: 'pro_carp_2',
    skills: ['Carpentry', 'Modular Furniture', 'Hinges', 'Door Locks', 'Cabinet Repair'],
    location: { city: 'Kolkata', address: 'Alipore, Kolkata', coordinates: [88.3312, 22.5312] },
    services: [
      { name: 'Door Lock / Deadbolt Installation', slug: 'carpenter', price: 349, priceType: 'starts_at', description: 'Mortise lock, latch, and safety handle fitting.' },
      { name: 'Modular Furniture & Bed Frame Assembly', slug: 'carpenter', price: 599, priceType: 'starts_at', description: 'Precision alignment for engineered wood sets.' },
    ],
    userId: { avatar: 'https://images.unsplash.com/photo-1506794778202-cad84cf45f1d?auto=format&fit=crop&w=200&q=80' },
  },
  {
    _id: 'pro_carp_2',
    businessName: 'Heritage Timber & Modern Joinery',
    category: 'carpenter',
    tagline: 'Door Hinge Alignment & Furniture Repairs • Slots Open',
    description: 'Skilled woodworkers for squeaky door repair, drawer channel replacement, shelf installations, and custom plywood work.',
    experienceYears: 8,
    rating: 4.9,
    totalReviews: 59,
    completedJobs: 59,
    responseRate: 97,
    trustScore: 91,
    trustTier: 'Elite Pro',
    verificationStatus: 'VERIFIED',
    availabilityType: 'available_now',
    leadTimeNotice: 'Available Tomorrow with open slots!',
    alternativeProId: 'pro_carp_1',
    skills: ['Carpentry', 'Door Alignment', 'Drawer Channels', 'Wall Shelves'],
    location: { city: 'Kolkata', address: 'Behala, Kolkata', coordinates: [88.3188, 22.4988] },
    services: [
      { name: 'Drawer Channel & Soft-Close Hinge Fitting', slug: 'carpenter', price: 299, priceType: 'starts_at', description: 'Telescopic channel installation and hinge adjustment.' },
      { name: 'Wooden Door Trimming & Planing', slug: 'carpenter', price: 399, priceType: 'fixed', description: 'Planing swollen doors for smooth latching.' },
    ],
    userId: { avatar: 'https://images.unsplash.com/photo-1560250097-0b93528c311a?auto=format&fit=crop&w=200&q=80' },
  },

  // 6. PAINTERS (2 Specialists)
  {
    _id: 'pro_paint_1',
    businessName: 'ColorCraft Premium Wall Specialists',
    category: 'painter',
    tagline: 'Dust-Free Spray Painting & Waterproof Texture Coats',
    description: 'Expert residential painting using Asian Paints Royale and Berger finishes. Moisture meter wall diagnostics and complete masking protection.',
    experienceYears: 9,
    rating: 4.9,
    totalReviews: 70,
    completedJobs: 70,
    responseRate: 96,
    trustScore: 93,
    trustTier: 'Elite Pro',
    verificationStatus: 'VERIFIED',
    availabilityType: 'booked_until_nov',
    leadTimeNotice: 'Booked through September & October. Earliest open booking starts November 2026.',
    alternativeProId: 'pro_paint_2',
    skills: ['Painting', 'Waterproofing', 'Texture Wall', 'Emulsion Finish'],
    location: { city: 'Kolkata', address: 'Salt Lake City, Kolkata', coordinates: [88.4112, 22.5812] },
    services: [
      { name: '1 Room Accent Wall Texture Painting', slug: 'painter', price: 1499, priceType: 'fixed', description: 'Metallic and stucco texture application with primer.' },
      { name: 'Dampness Inspection & Wall Sealer Application', slug: 'painter', price: 799, priceType: 'starts_at', description: 'Elastomeric waterproofing base coat treatment.' },
    ],
    userId: { avatar: 'https://images.unsplash.com/photo-1522075469751-3a6694fb2f61?auto=format&fit=crop&w=200&q=80' },
  },
  {
    _id: 'pro_paint_2',
    businessName: 'Rainbow Home Finishes & Textures',
    category: 'painter',
    tagline: 'Quick Touch-Up & Single Room Painting • Slots Open',
    description: 'Fast and affordable touch-up painting for rental move-outs, ceiling water stain covering, and door/window enamel repainting.',
    experienceYears: 6,
    rating: 4.7,
    totalReviews: 41,
    completedJobs: 41,
    responseRate: 95,
    trustScore: 86,
    trustTier: 'Verified Master',
    verificationStatus: 'VERIFIED',
    availabilityType: 'available_now',
    leadTimeNotice: 'Available Tomorrow with open slots!',
    alternativeProId: 'pro_paint_1',
    skills: ['Painting', 'Rental Touch-Up', 'Ceiling Stain', 'Enamel Paint'],
    location: { city: 'Kolkata', address: 'Rajarhat, Kolkata', coordinates: [88.4612, 22.6112] },
    services: [
      { name: 'Single Room Rapid Refresh Painting', slug: 'painter', price: 999, priceType: 'starts_at', description: 'Two coats of premium acrylic emulsion with masking.' },
      { name: 'Wood & Metal Grille Enamel Painting', slug: 'painter', price: 499, priceType: 'starts_at', description: 'Anti-rust primer and glossy enamel coat.' },
    ],
    userId: { avatar: 'https://images.unsplash.com/photo-1539571696357-5a69c17a67c6?auto=format&fit=crop&w=200&q=80' },
  },

  // 7. PEST CONTROL (2 Specialists)
  {
    _id: 'pro_pest_1',
    businessName: 'ShieldGuard Organic Pest Control',
    category: 'pest-control',
    tagline: 'Odorless Herbal Spray & German Gel Technology',
    description: 'Child-safe and pet-safe pest eradication for termites, cockroaches, bedbugs, and rodents with a 90-day re-service warranty.',
    experienceYears: 7,
    rating: 4.9,
    totalReviews: 58,
    completedJobs: 58,
    responseRate: 98,
    trustScore: 91,
    trustTier: 'Elite Pro',
    verificationStatus: 'VERIFIED',
    availabilityType: 'booked_until_nov',
    leadTimeNotice: 'Booked through September & October. Earliest open booking starts November 2026.',
    alternativeProId: 'pro_pest_2',
    skills: ['Pest Control', 'Termite Eradication', 'Cockroach Gel', 'Bedbug Heat Treatment'],
    location: { city: 'Kolkata', address: 'Salt Lake City, Kolkata', coordinates: [88.4112, 22.5812] },
    services: [
      { name: 'Odorless Cockroach Herbal Gel Treatment (2 BHK)', slug: 'pest-control', price: 749, priceType: 'fixed', description: 'Long-lasting Bayer gel application behind hinges and drains.' },
      { name: 'Complete Anti-Termite Drill & Injection Warranty', slug: 'pest-control', price: 1899, priceType: 'starts_at', description: 'Wall and woodwork chemical barrier installation.' },
    ],
    userId: { avatar: 'https://images.unsplash.com/photo-1522075469751-3a6694fb2f61?auto=format&fit=crop&w=200&q=80' },
  },
  {
    _id: 'pro_pest_2',
    businessName: 'BugZero Eco-Pest Exterminators',
    category: 'pest-control',
    tagline: 'Same-Day Ant & Cockroach Defense • Slots Open',
    description: 'Eco-certified pest control team for quick kitchen infestation treatment, mosquito fogging, and rodent bait boxes.',
    experienceYears: 5,
    rating: 4.8,
    totalReviews: 46,
    completedJobs: 46,
    responseRate: 97,
    trustScore: 88,
    trustTier: 'Verified Master',
    verificationStatus: 'VERIFIED',
    availabilityType: 'available_now',
    leadTimeNotice: 'Available Tomorrow with open slots!',
    alternativeProId: 'pro_pest_1',
    skills: ['Pest Control', 'Ants', 'Mosquito Fogging', 'Rodent Control'],
    location: { city: 'Kolkata', address: 'Lake Gardens, Kolkata', coordinates: [88.3550, 22.5020] },
    services: [
      { name: 'Targeted Kitchen Cockroach & Ant Barrier', slug: 'pest-control', price: 599, priceType: 'fixed', description: 'Food-safe gel dotting across cabinets and under-sink areas.' },
      { name: 'Indoor Mosquito & Fly Misting Treatment', slug: 'pest-control', price: 449, priceType: 'fixed', description: 'Pyrethrum-based botanical spray for zero residue.' },
    ],
    userId: { avatar: 'https://images.unsplash.com/photo-1508214751196-bcfd4ca60f91?auto=format&fit=crop&w=200&q=80' },
  },

  // 8. SMART HOME (2 Specialists)
  {
    _id: 'pro_smart_1',
    businessName: 'Apex Smart Home & CCTV Automation',
    category: 'smart-home',
    tagline: 'IP Security Cameras • Smart Switches • WiFi Mesh',
    description: 'Complete home automation, smart touch panel installation, video doorbells, and high-definition NVR surveillance setups.',
    experienceYears: 5,
    rating: 4.8,
    totalReviews: 44,
    completedJobs: 44,
    responseRate: 94,
    trustScore: 88,
    trustTier: 'Verified Master',
    verificationStatus: 'VERIFIED',
    availabilityType: 'booked_until_nov',
    leadTimeNotice: 'Booked through September & October. Earliest open booking starts November 2026.',
    alternativeProId: 'pro_smart_2',
    skills: ['Smart Home', 'CCTV Setup', 'Video Doorbell', 'WiFi Mesh'],
    location: { city: 'Kolkata', address: 'Rajarhat, Kolkata', coordinates: [88.4712, 22.6212] },
    services: [
      { name: 'Smart Switchboard & App Automation (per room)', slug: 'smart-home', price: 899, priceType: 'starts_at', description: 'Integration of smart modules with existing switchboards.' },
      { name: '4-Camera HD Night-Vision CCTV Setup & Cabling', slug: 'smart-home', price: 2499, priceType: 'fixed', description: 'Camera mounting, DVR configuration, and mobile app streaming.' },
    ],
    userId: { avatar: 'https://images.unsplash.com/photo-1519085360753-af0119f7cbe7?auto=format&fit=crop&w=200&q=80' },
  },
  {
    _id: 'pro_smart_2',
    businessName: 'FutureTech Automated Living & Security',
    category: 'smart-home',
    tagline: 'Smart Locks & Video Doorbell Setup • Slots Open',
    description: 'Rapid setup for digital smart door locks (Yale, Godrej, Aqara), Alexa/Google Home routines, and mesh WiFi range extension.',
    experienceYears: 4,
    rating: 4.9,
    totalReviews: 38,
    completedJobs: 38,
    responseRate: 98,
    trustScore: 90,
    trustTier: 'Elite Pro',
    verificationStatus: 'VERIFIED',
    availabilityType: 'available_now',
    leadTimeNotice: 'Available Tomorrow with open slots!',
    alternativeProId: 'pro_smart_1',
    skills: ['Smart Home', 'Smart Door Locks', 'Alexa Setup', 'WiFi Extension'],
    location: { city: 'Kolkata', address: 'EM Bypass / Ruby, Kolkata', coordinates: [88.3988, 22.5122] },
    services: [
      { name: 'Biometric Smart Door Lock Installation', slug: 'smart-home', price: 999, priceType: 'fixed', description: 'Mortise woodwork routing, strike plate alignment, and app pairing.' },
      { name: 'WiFi Video Doorbell Mounting & Sync', slug: 'smart-home', price: 649, priceType: 'fixed', description: 'Chime wiring, camera angle tuning, and two-way audio verification.' },
    ],
    userId: { avatar: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?auto=format&fit=crop&w=200&q=80' },
  },
];
