export const FALLBACK_CATEGORIES = [
  { _id: 'cat_1', name: 'Electrical Repairs & Wiring', slug: 'electrician', icon: '⚡', basePrice: 299, description: 'Complete electrical troubleshooting, circuit breaker replacement, wiring repairs, and installations.' },
  { _id: 'cat_2', name: 'AC Servicing & Deep Repair', slug: 'ac-repair', icon: '❄️', basePrice: 549, description: 'Jet pump foam wash, gas leak inspection & recharge, PCB troubleshooting, and maintenance.' },
  { _id: 'cat_3', name: 'Plumbing & Pipe Solutions', slug: 'plumber', icon: '🔧', basePrice: 349, description: 'Emergency leak detection, tap & mixer fitting, drain unblocking, water heater setup, and more.' },
  { _id: 'cat_4', name: 'Full Home Deep Cleaning', slug: 'cleaning', icon: '✨', basePrice: 1299, description: 'Intensive hospital-grade sanitization for kitchens, bathrooms, floors, and upholstery.' },
  { _id: 'cat_5', name: 'Carpentry & Woodwork Assembly', slug: 'carpenter', icon: '🪚', basePrice: 449, description: 'Custom cabinetry repairs, door/lock fixing, hinges, modular furniture setup, and precision work.' },
  { _id: 'cat_6', name: 'Interior & Exterior Painting', slug: 'painter', icon: '🎨', basePrice: 1499, description: 'Waterproofing, wall crack treatment, texture painting, and premium emulsion finishes.' },
  { _id: 'cat_7', name: 'Organic Pest Control', slug: 'pest-control', icon: '🛡️', basePrice: 749, description: 'Odorless gel & herbal spray treatment for cockroaches, termites, bedbugs, and rodents.' },
  { _id: 'cat_8', name: 'Smart Home & CCTV Setup', slug: 'smart-home', icon: '📡', basePrice: 899, description: 'Smart switch configuration, IP camera and video doorbell installations, WiFi mesh, and more.' },
];

export const FALLBACK_PROS = [
  // ==========================================
  // 1. KOLKATA PROFESSIONALS
  // ==========================================
  {
    _id: 'pro_kol_1',
    businessName: 'Apex Electricals & Power Systems',
    ownerName: 'Subhashish Das',
    category: 'electrician',
    tagline: 'Licensed Master Electrician • Lead: Subhashish Das',
    description: 'Specializing in residential wiring, short-circuit troubleshooting, circuit breaker upgrades, inverter setup, and emergency power restoration across Salt Lake and New Town.',
    experienceYears: 9,
    rating: 4.9,
    totalReviews: 92,
    completedJobs: 92,
    responseRate: 99,
    trustScore: 95,
    trustTier: 'Elite Pro',
    verificationStatus: 'VERIFIED',
    availabilityType: 'booked_until_nov',
    leadTimeNotice: 'Booked through September & October. Earliest open booking starts November 2026.',
    alternativeProId: 'pro_kol_2',
    skills: ['Electrician', 'Inverter Setup', 'Short Circuit', 'Earthing', 'Home Automation'],
    location: { city: 'Kolkata', address: 'Salt Lake Sector V, Kolkata', coordinates: [88.4312, 22.5769] },
    services: [
      { name: 'Electrical Diagnostics & Wiring Fault Rectification', slug: 'electrician', price: 299, priceType: 'starts_at', description: 'Complete circuit inspection with safety testing.' },
      { name: 'Inverter & Battery Wiring Installation', slug: 'electrician', price: 699, priceType: 'fixed', description: 'Full inverter bypass switch installation and heavy gauge connection.' },
    ],
    userId: {
      name: 'Subhashish Das',
      avatar: 'https://images.unsplash.com/photo-1540569014015-19a7be504e3a?auto=format&fit=crop&w=250&q=80',
    },
  },
  {
    _id: 'pro_kol_2',
    businessName: 'VoltMaster Quick Response Electricians',
    ownerName: 'Debabrata Mukherjee',
    category: 'electrician',
    tagline: 'Emergency Dispatch Electrician • Lead: Debabrata Mukherjee',
    description: 'Fast-response electrician service for immediate switchboard replacement, fan regulator repairs, LED track lighting, and household power faults.',
    experienceYears: 6,
    rating: 4.8,
    totalReviews: 64,
    completedJobs: 64,
    responseRate: 97,
    trustScore: 89,
    trustTier: 'Verified Master',
    verificationStatus: 'VERIFIED',
    availabilityType: 'available_now',
    leadTimeNotice: 'Available Tomorrow with open morning and afternoon slots!',
    alternativeProId: 'pro_kol_1',
    skills: ['Electrician', 'Emergency Repairs', 'Switchboard Setup', 'Light Fitting'],
    location: { city: 'Kolkata', address: 'Park Circus, Kolkata', coordinates: [88.3698, 22.5448] },
    services: [
      { name: 'Rapid Power Fault & Switchboard Fix', slug: 'electrician', price: 249, priceType: 'starts_at', description: 'Fast diagnostics and replacement of sockets and switches.' },
      { name: 'Ceiling Fan & Chandelier Fitting', slug: 'electrician', price: 349, priceType: 'fixed', description: 'Secure ceiling anchor mounting with dynamic balance check.' },
    ],
    userId: {
      name: 'Debabrata Mukherjee',
      avatar: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?auto=format&fit=crop&w=250&q=80',
    },
  },
  {
    _id: 'pro_kol_3',
    businessName: 'Metro Air Conditioning & Cooling',
    ownerName: 'Amitava Roy',
    category: 'ac-repair',
    tagline: 'High-Pressure Jet Pump Foam Servicing • Lead: Amitava Roy',
    description: 'Over 8 years servicing split and window ACs across Kolkata, Park Street, and Ballygunge. 100% genuine copper coils and refrigerant gas guarantee.',
    experienceYears: 8,
    rating: 4.8,
    totalReviews: 78,
    completedJobs: 78,
    responseRate: 97,
    trustScore: 92,
    trustTier: 'Elite Pro',
    verificationStatus: 'VERIFIED',
    availabilityType: 'booked_until_nov',
    leadTimeNotice: 'Booked through September & October. Earliest open booking starts November 2026.',
    alternativeProId: 'pro_kol_4',
    skills: ['AC Repair', 'Jet Foam Wash', 'Gas Recharge', 'PCB Repair', 'Compressor Check'],
    location: { city: 'Kolkata', address: 'Park Street, Kolkata', coordinates: [88.3524, 22.5511] },
    services: [
      { name: 'Jet Pump Deep Foam AC Cleaning', slug: 'ac-repair', price: 549, priceType: 'starts_at', description: 'High pressure water jet coil cleaning and drain wash.' },
      { name: 'R32 / R410A Refrigerant Gas Top-up', slug: 'ac-repair', price: 1899, priceType: 'starts_at', description: 'Nitrogen leak detection followed by pressurized refrigerant fill.' },
    ],
    userId: {
      name: 'Amitava Roy',
      avatar: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?auto=format&fit=crop&w=250&q=80',
    },
  },
  {
    _id: 'pro_kol_4',
    businessName: 'CoolBreeze Express AC Care',
    ownerName: 'Pritam Ghosh',
    category: 'ac-repair',
    tagline: 'Fast AC Servicing & Water Leak Fix • Lead: Pritam Ghosh',
    description: 'Rapid cooling troubleshooting, anti-bacterial filter sanitation, water drip elimination, and indoor blower servicing in New Town and Rajarhat.',
    experienceYears: 5,
    rating: 4.7,
    totalReviews: 52,
    completedJobs: 52,
    responseRate: 95,
    trustScore: 87,
    trustTier: 'Verified Master',
    verificationStatus: 'VERIFIED',
    availabilityType: 'available_now',
    leadTimeNotice: 'Available Tomorrow with open slots!',
    alternativeProId: 'pro_kol_3',
    skills: ['AC Repair', 'Water Leakage', 'Capacitor Change', 'Filter Cleaning'],
    location: { city: 'Kolkata', address: 'New Town Action Area 2, Kolkata', coordinates: [88.4812, 22.5955] },
    services: [
      { name: 'AC Drain Leakage & Water Drip Fix', slug: 'ac-repair', price: 399, priceType: 'fixed', description: 'Unclog drain lines and seal indoor tray joints.' },
      { name: 'Comprehensive Split AC General Service', slug: 'ac-repair', price: 499, priceType: 'fixed', description: 'Filter cleaning, coil washing, and amperage testing.' },
    ],
    userId: {
      name: 'Pritam Ghosh',
      avatar: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?auto=format&fit=crop&w=250&q=80',
    },
  },
  {
    _id: 'pro_kol_5',
    businessName: 'Prime Plumbing & Leak Solutions',
    ownerName: 'Sunil Mahato',
    category: 'plumber',
    tagline: 'Master Plumber • Lead: Sunil Mahato',
    description: 'Reliable plumbing services across South Kolkata: Ballygunge, Gariahat, and Jadavpur. Sanitary fittings, overhead tank floats, and motorized drain unblocking.',
    experienceYears: 11,
    rating: 4.9,
    totalReviews: 110,
    completedJobs: 110,
    responseRate: 98,
    trustScore: 96,
    trustTier: 'Elite Pro',
    verificationStatus: 'VERIFIED',
    availabilityType: 'available_now',
    skills: ['Plumbing', 'Drain Cleaning', 'Tap Mixer', 'Water Tank Float', 'Geyser Fitting'],
    location: { city: 'Kolkata', address: 'Ballygunge, Kolkata', coordinates: [88.3653, 22.5280] },
    services: [
      { name: 'Concealed Pipe Leakage Detection & Repair', slug: 'plumber', price: 349, priceType: 'starts_at', description: 'Instant detection and repair with quality PVC/CPVC.' },
      { name: 'Motorized High-Torque Drain Unblocking', slug: 'plumber', price: 599, priceType: 'fixed', description: 'Heavy duty steel snake clearing bathroom and kitchen lines.' },
    ],
    userId: {
      name: 'Sunil Mahato',
      avatar: 'https://images.unsplash.com/photo-1519085360753-af0119f7cbe7?auto=format&fit=crop&w=250&q=80',
    },
  },
  {
    _id: 'pro_kol_6',
    businessName: 'PureSpark Deep Cleaning & Sanitization',
    ownerName: 'Rina Banerjee',
    category: 'cleaning',
    tagline: 'Hospital Grade Sanitization • Lead: Rina Banerjee',
    description: 'Intensive deep cleaning solutions for apartments, villas, and commercial offices in New Town and Salt Lake.',
    experienceYears: 6,
    rating: 4.9,
    totalReviews: 65,
    completedJobs: 65,
    responseRate: 96,
    trustScore: 94,
    trustTier: 'Elite Pro',
    verificationStatus: 'VERIFIED',
    availabilityType: 'available_now',
    skills: ['Deep Cleaning', 'Sanitization', 'Kitchen Scrub', 'Bathroom Descaling', 'Sofa Shampoo'],
    location: { city: 'Kolkata', address: 'Salt Lake Sector III, Kolkata', coordinates: [88.4112, 22.5712] },
    services: [
      { name: 'Complete 2BHK Intensive Deep Sanitization', slug: 'cleaning', price: 2199, priceType: 'starts_at', description: 'Machine scrubbing of floors, kitchen degreasing, and bathrooms.' },
      { name: 'Antibacterial Bathroom Steam & Descaling', slug: 'cleaning', price: 599, priceType: 'fixed', description: 'Limescale removal from tiles, glass partitions, and fittings.' },
    ],
    userId: {
      name: 'Rina Banerjee',
      avatar: 'https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?auto=format&fit=crop&w=250&q=80',
    },
  },

  // ==========================================
  // 2. BENGALURU PROFESSIONALS
  // ==========================================
  {
    _id: 'pro_blr_1',
    businessName: 'Silicon Valley Electricals & Smart Wiring',
    ownerName: 'Karthik Murthy',
    category: 'electrician',
    tagline: 'Smart Homes & Circuit Specialist • Lead: Karthik Murthy',
    description: 'Expert residential electrician catering to IT corridors in Koramangala, HSR Layout, Indiranagar, and Bellandur. High-voltage wiring, EV charger installation, and automated circuit panels.',
    experienceYears: 8,
    rating: 4.9,
    totalReviews: 87,
    completedJobs: 87,
    responseRate: 98,
    trustScore: 96,
    trustTier: 'Elite Pro',
    verificationStatus: 'VERIFIED',
    availabilityType: 'available_now',
    skills: ['Electrician', 'EV Charger', 'Smart Switches', 'DB Panel Repair', 'Short Circuit'],
    location: { city: 'Bengaluru', address: 'Koramangala 5th Block, Bengaluru', coordinates: [77.6245, 12.9352] },
    services: [
      { name: 'Comprehensive Short-Circuit Diagnostics', slug: 'electrician', price: 349, priceType: 'starts_at', description: 'Complete circuit inspection with safety breaker replacement.' },
      { name: 'Home EV Charger Dedicated Line Setup', slug: 'electrician', price: 1499, priceType: 'fixed', description: 'Heavy 4-sqmm cabling with dedicated MCB and earthing.' },
    ],
    userId: {
      name: 'Karthik Murthy',
      avatar: 'https://images.unsplash.com/photo-1492562080023-ab3db95bfbce?auto=format&fit=crop&w=250&q=80',
    },
  },
  {
    _id: 'pro_blr_2',
    businessName: 'Garden City AC Cooling Systems',
    ownerName: 'Suresh Gowda',
    category: 'ac-repair',
    tagline: 'Inverter AC & VRV Specialist • Lead: Suresh Gowda',
    description: 'Fast doorstep AC servicing across Indiranagar, Whitefield, and Marathahalli. Jet pump deep foam wash, PCB board repair, and eco-friendly gas top-ups.',
    experienceYears: 7,
    rating: 4.8,
    totalReviews: 72,
    completedJobs: 72,
    responseRate: 99,
    trustScore: 93,
    trustTier: 'Elite Pro',
    verificationStatus: 'VERIFIED',
    availabilityType: 'available_now',
    skills: ['AC Repair', 'Inverter AC', 'Jet Foam Cleaning', 'Gas Top-up', 'PCB Soldering'],
    location: { city: 'Bengaluru', address: 'Indiranagar 100ft Road, Bengaluru', coordinates: [77.6412, 12.9784] },
    services: [
      { name: 'Jet Foam Deep Wash & Anti-Bacterial Treatment', slug: 'ac-repair', price: 599, priceType: 'starts_at', description: 'Double high pressure wash with disinfectant shield.' },
      { name: 'Inverter AC PCB Circuit Board Diagnostics', slug: 'ac-repair', price: 899, priceType: 'starts_at', description: 'Component micro-soldering with warranty.' },
    ],
    userId: {
      name: 'Suresh Gowda',
      avatar: 'https://images.unsplash.com/photo-1506794778202-cad84cf45f1d?auto=format&fit=crop&w=250&q=80',
    },
  },
  {
    _id: 'pro_blr_3',
    businessName: 'Namma Plumbers QuickFix',
    ownerName: 'Ramesh Rao',
    category: 'plumber',
    tagline: 'High Pressure Water & Sump Experts • Lead: Ramesh Rao',
    description: 'Doorstep plumbing solutions in HSR Layout, Sarjapur Road, and BTM. Hydro-jet drain unblocking, Grohe/Kohler mixer replacement, and pressure pump installation.',
    experienceYears: 10,
    rating: 4.9,
    totalReviews: 95,
    completedJobs: 95,
    responseRate: 98,
    trustScore: 95,
    trustTier: 'Elite Pro',
    verificationStatus: 'VERIFIED',
    availabilityType: 'available_now',
    skills: ['Plumbing', 'Pressure Pump', 'Leak Detection', 'Drain Clearing', 'Sanitary Fittings'],
    location: { city: 'Bengaluru', address: 'HSR Layout Sector 2, Bengaluru', coordinates: [77.6387, 12.9121] },
    services: [
      { name: 'Emergency Concealed Pipe Leakage Fix', slug: 'plumber', price: 399, priceType: 'starts_at', description: 'Thermal camera detection with zero needless tile breaking.' },
      { name: 'Pressure Booster Pump Installation', slug: 'plumber', price: 999, priceType: 'fixed', description: 'Complete bypass connection and automated pressure switch tuning.' },
    ],
    userId: {
      name: 'Ramesh Rao',
      avatar: 'https://images.unsplash.com/photo-1522075469751-3a6694fb2f61?auto=format&fit=crop&w=250&q=80',
    },
  },
  {
    _id: 'pro_blr_4',
    businessName: 'EcoSpark Bengaluru Home Sanitization',
    ownerName: 'Divya Hegde',
    category: 'cleaning',
    tagline: 'Deep Cleaning & Fabric Steaming • Lead: Divya Hegde',
    description: 'Hospital-grade steam sanitation for tech parks, apartments, and villas across Whitefield, Electronic City, and Bellandur.',
    experienceYears: 6,
    rating: 4.8,
    totalReviews: 61,
    completedJobs: 61,
    responseRate: 97,
    trustScore: 92,
    trustTier: 'Elite Pro',
    verificationStatus: 'VERIFIED',
    availabilityType: 'available_now',
    skills: ['Deep Cleaning', 'Sofa Shampoo', 'Steam Sanitization', 'Balcony Wash', 'Kitchen Degreasing'],
    location: { city: 'Bengaluru', address: 'Whitefield Main Road, Bengaluru', coordinates: [77.7499, 12.9698] },
    services: [
      { name: 'Full 3BHK Villa Eco-Sanitization', slug: 'cleaning', price: 2899, priceType: 'starts_at', description: 'Deep floor buffing, bathroom descaling, and upholstery steaming.' },
      { name: 'Kitchen Modular Degreasing & Chimney Wash', slug: 'cleaning', price: 799, priceType: 'fixed', description: 'High-temperature steam clearing hardened oil deposits.' },
    ],
    userId: {
      name: 'Divya Hegde',
      avatar: 'https://images.unsplash.com/photo-1580489944761-15a19d654956?auto=format&fit=crop&w=250&q=80',
    },
  },

  // ==========================================
  // 3. DELHI NCR PROFESSIONALS
  // ==========================================
  {
    _id: 'pro_del_1',
    businessName: 'Capital Power & Electrical Solutions',
    ownerName: 'Rajesh Sharma',
    category: 'electrician',
    tagline: 'Licensed Heavy Wiring Electrician • Lead: Rajesh Sharma',
    description: 'Expert residential and commercial electrician across South Extension, Connaught Place, Vasant Kunj, and Gurgaon Cyber City. 3-phase load distribution and MCB overhauls.',
    experienceYears: 12,
    rating: 4.9,
    totalReviews: 104,
    completedJobs: 104,
    responseRate: 99,
    trustScore: 97,
    trustTier: 'Elite Pro',
    verificationStatus: 'VERIFIED',
    availabilityType: 'available_now',
    skills: ['Electrician', '3-Phase Wiring', 'Short Circuit', 'Generator Bypass', 'Smart Lighting'],
    location: { city: 'Delhi NCR', address: 'Connaught Place, New Delhi', coordinates: [77.2167, 28.6315] },
    services: [
      { name: 'Heavy 3-Phase Load Balance & MCB Upgrade', slug: 'electrician', price: 499, priceType: 'starts_at', description: 'Complete DB box balance testing with safety relay.' },
      { name: 'Rapid Household Short-Circuit Emergency Fix', slug: 'electrician', price: 349, priceType: 'starts_at', description: 'Instant fault tracing and wiring repair.' },
    ],
    userId: {
      name: 'Rajesh Sharma',
      avatar: 'https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?auto=format&fit=crop&w=250&q=80',
    },
  },
  {
    _id: 'pro_del_2',
    businessName: 'FrostAir Express AC Care Delhi NCR',
    ownerName: 'Vikas Verma',
    category: 'ac-repair',
    tagline: 'Heavy Jet Pump AC Wash & Gas Leak Fix • Lead: Vikas Verma',
    description: 'Servicing Gurgaon DLF, Noida Sector 18, and South Delhi. Specialized in high-ambient temperature cooling performance, outdoor coil descaling, and condenser replacement.',
    experienceYears: 9,
    rating: 4.8,
    totalReviews: 89,
    completedJobs: 89,
    responseRate: 96,
    trustScore: 94,
    trustTier: 'Elite Pro',
    verificationStatus: 'VERIFIED',
    availabilityType: 'available_now',
    skills: ['AC Repair', 'Gas Leakage Fix', 'Jet Pump Wash', 'Compressor Replacement'],
    location: { city: 'Delhi NCR', address: 'DLF Phase 2, Gurgaon (NCR)', coordinates: [77.0869, 28.4817] },
    services: [
      { name: 'Intensive Jet Pump Outdoor & Indoor Coil Wash', slug: 'ac-repair', price: 599, priceType: 'fixed', description: 'Pressure foam cleaning with fin comb straightening.' },
      { name: 'Refrigerant Gas Leak Detection & 100% Recharge', slug: 'ac-repair', price: 1999, priceType: 'starts_at', description: 'Pressure testing with nitrogen and genuine R32/R410A gas.' },
    ],
    userId: {
      name: 'Vikas Verma',
      avatar: 'https://images.unsplash.com/photo-1519085360753-af0119f7cbe7?auto=format&fit=crop&w=250&q=80',
    },
  },
  {
    _id: 'pro_del_3',
    businessName: 'Royal Plumbers & Pipeline Tech',
    ownerName: 'Amit Tyagi',
    category: 'plumber',
    tagline: 'Emergency Pipeline & Sensor Taps • Lead: Amit Tyagi',
    description: 'Precision plumbing across Noida, Greater Noida, and East Delhi. Commercial sensor taps, RO water line installation, and underground pipe burst repairs.',
    experienceYears: 8,
    rating: 4.8,
    totalReviews: 68,
    completedJobs: 68,
    responseRate: 98,
    trustScore: 91,
    trustTier: 'Elite Pro',
    verificationStatus: 'VERIFIED',
    availabilityType: 'available_now',
    skills: ['Plumbing', 'RO Pipeline', 'Sensor Taps', 'Pipe Burst', 'Bathroom Syphon'],
    location: { city: 'Delhi NCR', address: 'Sector 18, Noida (NCR)', coordinates: [77.3260, 28.5708] },
    services: [
      { name: 'Bathroom Concealed Diverter & Mixer Fitting', slug: 'plumber', price: 449, priceType: 'starts_at', description: 'Precision multi-valve installation with zero leakage guarantee.' },
      { name: 'Water Geyser Pipe Descaling & Replacement', slug: 'plumber', price: 399, priceType: 'fixed', description: 'Flexible SS braided pipe fitting with safety valve.' },
    ],
    userId: {
      name: 'Amit Tyagi',
      avatar: 'https://images.unsplash.com/photo-1506794778202-cad84cf45f1d?auto=format&fit=crop&w=250&q=80',
    },
  },

  // ==========================================
  // 4. MUMBAI PROFESSIONALS
  // ==========================================
  {
    _id: 'pro_mum_1',
    businessName: 'Coastal City Electricals & Inverters',
    ownerName: 'Siddharth Kadam',
    category: 'electrician',
    tagline: 'Moisture-Proof Marine Grade Wiring • Lead: Siddharth Kadam',
    description: 'Specializing in monsoon waterproofing for wiring, anti-corrosion switchboards, inverter backup setups, and apartment electrical audits across Bandra, Juhu, and Khar.',
    experienceYears: 10,
    rating: 4.9,
    totalReviews: 98,
    completedJobs: 98,
    responseRate: 99,
    trustScore: 96,
    trustTier: 'Elite Pro',
    verificationStatus: 'VERIFIED',
    availabilityType: 'available_now',
    skills: ['Electrician', 'Waterproof Wiring', 'Inverter Setup', 'LED False Ceiling', 'Short Circuit'],
    location: { city: 'Mumbai', address: 'Bandra West (Linking Road), Mumbai', coordinates: [72.8333, 19.0596] },
    services: [
      { name: 'Monsoon Anti-Dampness Electrical Isolation', slug: 'electrician', price: 399, priceType: 'starts_at', description: 'High-resistance insulation testing and waterproof switch boxes.' },
      { name: 'Heavy Appliance Dedicated MCB Wiring', slug: 'electrician', price: 549, priceType: 'fixed', description: 'Safe dedicated line for microwave, oven, and washing machine.' },
    ],
    userId: {
      name: 'Siddharth Kadam',
      avatar: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?auto=format&fit=crop&w=250&q=80',
    },
  },
  {
    _id: 'pro_mum_2',
    businessName: 'Bombay Cooling & AC Care Services',
    ownerName: 'Sachin Deshmukh',
    category: 'ac-repair',
    tagline: 'Anti-Rust Copper Coil AC Servicing • Lead: Sachin Deshmukh',
    description: 'Expert AC mechanics handling sea-salt rust prevention, anti-corrosion blue fin spray, indoor unit jet cleaning, and PCB repair in Andheri, Powai, and Goregaon.',
    experienceYears: 8,
    rating: 4.8,
    totalReviews: 81,
    completedJobs: 81,
    responseRate: 97,
    trustScore: 93,
    trustTier: 'Elite Pro',
    verificationStatus: 'VERIFIED',
    availabilityType: 'available_now',
    skills: ['AC Repair', 'Anti-Rust Coating', 'Jet Wash', 'Gas Filling', 'Indoor Water Leak'],
    location: { city: 'Mumbai', address: 'Andheri East (Chakala), Mumbai', coordinates: [72.8697, 19.1136] },
    services: [
      { name: 'Anti-Rust Coating & High Pressure Jet Clean', slug: 'ac-repair', price: 649, priceType: 'starts_at', description: 'Protective polymer resin coating on external coils.' },
      { name: 'Indoor AC Water Overflow Line Vacuuming', slug: 'ac-repair', price: 399, priceType: 'fixed', description: 'Clear clogged drain lines and prevent wall damage.' },
    ],
    userId: {
      name: 'Sachin Deshmukh',
      avatar: 'https://images.unsplash.com/photo-1492562080023-ab3db95bfbce?auto=format&fit=crop&w=250&q=80',
    },
  },
  {
    _id: 'pro_mum_3',
    businessName: 'Marine Lines Rapid Plumbing',
    ownerName: 'Rohan Patil',
    category: 'plumber',
    tagline: 'High Pressure Water Line & Sump Pumps • Lead: Rohan Patil',
    description: 'Fast response plumbing across South Mumbai and Central suburbs: Lower Parel, Dadar, Worli, and Powai. Pressure pumps, sewer line unclogging, and bathroom fixture installation.',
    experienceYears: 9,
    rating: 4.8,
    totalReviews: 76,
    completedJobs: 76,
    responseRate: 98,
    trustScore: 92,
    trustTier: 'Elite Pro',
    verificationStatus: 'VERIFIED',
    availabilityType: 'available_now',
    skills: ['Plumbing', 'Pressure Pump', 'Drain Cleaning', 'Mixer Taps', 'Flush Valve'],
    location: { city: 'Mumbai', address: 'Lower Parel, Mumbai', coordinates: [72.8311, 18.9950] },
    services: [
      { name: 'Emergency Drain Unclogging with Spiral Snake', slug: 'plumber', price: 549, priceType: 'fixed', description: 'Fast motorized clearing of bathroom and kitchen drains.' },
      { name: 'Luxury Shower & Concealed Diverter Overhaul', slug: 'plumber', price: 499, priceType: 'starts_at', description: 'Cartridge replacement and dynamic water balancing.' },
    ],
    userId: {
      name: 'Rohan Patil',
      avatar: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?auto=format&fit=crop&w=250&q=80',
    },
  },

  // ==========================================
  // 5. HYDERABAD PROFESSIONALS
  // ==========================================
  {
    _id: 'pro_hyd_1',
    businessName: 'CyberCity Electricals & Automation',
    ownerName: 'Venkat Reddy',
    category: 'electrician',
    tagline: 'IoT Smart Automation & Electricals • Lead: Venkat Reddy',
    description: 'Serving Hitec City, Gachibowli, Madhapur, and Jubilee Hills. Residential electrical wiring, smart lighting, high-amperage server room wiring, and backup inverter installations.',
    experienceYears: 10,
    rating: 4.9,
    totalReviews: 88,
    completedJobs: 88,
    responseRate: 99,
    trustScore: 96,
    trustTier: 'Elite Pro',
    verificationStatus: 'VERIFIED',
    availabilityType: 'available_now',
    skills: ['Electrician', 'Smart Switch', 'Inverter Setup', 'LED Strips', 'Power Tripping'],
    location: { city: 'Hyderabad', address: 'Hitec City, Madhapur, Hyderabad', coordinates: [78.3811, 17.4474] },
    services: [
      { name: 'Smart Home Touch Switch & WiFi Sync (Per Room)', slug: 'electrician', price: 799, priceType: 'fixed', description: 'Smart panel retrofitting with Google Home / Alexa.' },
      { name: 'Emergency Power Tripping & Earth Fault Rectification', slug: 'electrician', price: 349, priceType: 'starts_at', description: 'High-speed earth leakage detector and wiring patch.' },
    ],
    userId: {
      name: 'Venkat Reddy',
      avatar: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?auto=format&fit=crop&w=250&q=80',
    },
  },
  {
    _id: 'pro_hyd_2',
    businessName: 'Deccan Chillers AC & Refrigeration',
    ownerName: 'Srinivas Rao',
    category: 'ac-repair',
    tagline: 'Commercial & Residential Inverter AC • Lead: Srinivas Rao',
    description: 'High-capacity split and cassette AC servicing in Banjara Hills, Kondapur, and Kukatpally. Comprehensive coil wash, nitrogen pressure testing, and refrigerant recharge.',
    experienceYears: 8,
    rating: 4.8,
    totalReviews: 74,
    completedJobs: 74,
    responseRate: 97,
    trustScore: 92,
    trustTier: 'Elite Pro',
    verificationStatus: 'VERIFIED',
    availabilityType: 'available_now',
    skills: ['AC Repair', 'Cassette AC', 'Gas Top-up', 'Jet Wash', 'Blower Motor'],
    location: { city: 'Hyderabad', address: 'Banjara Hills Road No 12, Hyderabad', coordinates: [78.4419, 17.4156] },
    services: [
      { name: 'Twin Jet Foam Wash for Split AC Unit', slug: 'ac-repair', price: 549, priceType: 'fixed', description: 'Intense water jet cleaning for blower and external condenser.' },
      { name: 'Compressor Capacitor & Relay Replacement', slug: 'ac-repair', price: 699, priceType: 'starts_at', description: 'Heavy duty Japanese capacitor with 1-year replacement warranty.' },
    ],
    userId: {
      name: 'Srinivas Rao',
      avatar: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?auto=format&fit=crop&w=250&q=80',
    },
  },

  // ==========================================
  // 6. CHENNAI PROFESSIONALS
  // ==========================================
  {
    _id: 'pro_chn_1',
    businessName: 'Coromandel Electricals & Power Systems',
    ownerName: 'R. Balaji',
    category: 'electrician',
    tagline: 'High Amperage Residential Electrician • Lead: R. Balaji',
    description: 'Serving T. Nagar, Adyar, Anna Nagar, and Velachery. Circuit balance, heavy water heater wiring, ceiling fans, and complete distribution board servicing.',
    experienceYears: 11,
    rating: 4.9,
    totalReviews: 93,
    completedJobs: 93,
    responseRate: 98,
    trustScore: 95,
    trustTier: 'Elite Pro',
    verificationStatus: 'VERIFIED',
    availabilityType: 'available_now',
    skills: ['Electrician', 'Distribution Board', 'Wiring Overhaul', 'Inverter Bypass', 'Safety Breaker'],
    location: { city: 'Chennai', address: 'T. Nagar (Pondy Bazaar), Chennai', coordinates: [80.2337, 13.0418] },
    services: [
      { name: 'Complete Residential DB Panel Overhaul', slug: 'electrician', price: 449, priceType: 'starts_at', description: 'Load balance calibration and new miniature circuit breakers.' },
      { name: 'Geyser & Water Pump Safety Contactor Setup', slug: 'electrician', price: 349, priceType: 'fixed', description: 'Heavy gauge wiring with moisture-sealed contactor.' },
    ],
    userId: {
      name: 'R. Balaji',
      avatar: 'https://images.unsplash.com/photo-1519085360753-af0119f7cbe7?auto=format&fit=crop&w=250&q=80',
    },
  },
  {
    _id: 'pro_chn_2',
    businessName: 'Marina Cool Air Conditioners',
    ownerName: 'Sundaramurthy',
    category: 'ac-repair',
    tagline: 'High Humidity AC Performance Tech • Lead: Sundaramurthy',
    description: 'Combat Chennai heat and coastal humidity with specialized coil anti-corrosion treatment, deep jet foam wash, and R32 refrigerant recharge in Adyar, Besant Nagar, and OMR.',
    experienceYears: 9,
    rating: 4.8,
    totalReviews: 79,
    completedJobs: 79,
    responseRate: 97,
    trustScore: 93,
    trustTier: 'Elite Pro',
    verificationStatus: 'VERIFIED',
    availabilityType: 'available_now',
    skills: ['AC Repair', 'Anti-Corrosion Wash', 'Gas Recharge', 'Blower Motor', 'Water Leak'],
    location: { city: 'Chennai', address: 'Adyar (Lattice Bridge Road), Chennai', coordinates: [80.2570, 13.0012] },
    services: [
      { name: 'High Humidity Jet Foam Service & Anti-Bacterial Spray', slug: 'ac-repair', price: 549, priceType: 'fixed', description: 'Complete pressure cleaning for indoor cooling coil and outdoor unit.' },
      { name: 'Copper Line Braze & Complete Gas Refill', slug: 'ac-repair', price: 1899, priceType: 'starts_at', description: 'Silver solder brazing on cracked copper tubes and gas refill.' },
    ],
    userId: {
      name: 'Sundaramurthy',
      avatar: 'https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?auto=format&fit=crop&w=250&q=80',
    },
  },

  // ==========================================
  // 7. PUNE PROFESSIONALS
  // ==========================================
  {
    _id: 'pro_pun_1',
    businessName: 'Deccan Heritage Electricals',
    ownerName: 'Ganesh Joshi',
    category: 'electrician',
    tagline: 'Master Electrician & Automation • Lead: Ganesh Joshi',
    description: 'Serving Kothrud, Baner, Viman Nagar, and Hinjewadi IT Park. Residential power distribution, automated security lighting, inverter backup, and emergency short-circuit resolution.',
    experienceYears: 10,
    rating: 4.9,
    totalReviews: 85,
    completedJobs: 85,
    responseRate: 98,
    trustScore: 95,
    trustTier: 'Elite Pro',
    verificationStatus: 'VERIFIED',
    availabilityType: 'available_now',
    skills: ['Electrician', 'Short Circuit', 'Inverter Setup', 'Smart Home', 'Panel Upgrade'],
    location: { city: 'Pune', address: 'Kothrud (Paud Road), Pune', coordinates: [73.8180, 18.5074] },
    services: [
      { name: 'Complete Home Short-Circuit Inspection', slug: 'electrician', price: 299, priceType: 'starts_at', description: 'Fault tracing and rewiring of burnt out segments.' },
      { name: 'Solar Inverter Bypass & Heavy Cable Connection', slug: 'electrician', price: 749, priceType: 'fixed', description: 'Safe connection between solar hybrid inverter and mains DB.' },
    ],
    userId: {
      name: 'Ganesh Joshi',
      avatar: 'https://images.unsplash.com/photo-1506794778202-cad84cf45f1d?auto=format&fit=crop&w=250&q=80',
    },
  },
  {
    _id: 'pro_pun_2',
    businessName: 'Western Ghats Plumbing & Water Tech',
    ownerName: 'Pratik Kulkarni',
    category: 'plumber',
    tagline: 'High-Pressure Water Pipelines • Lead: Pratik Kulkarni',
    description: 'Expert plumbing across Hinjewadi, Wakad, Baner, and Aundh. Concealed leak repair, bathroom sanitary installations, hydro-jet drain cleaning, and water tank valve replacements.',
    experienceYears: 8,
    rating: 4.8,
    totalReviews: 70,
    completedJobs: 70,
    responseRate: 98,
    trustScore: 92,
    trustTier: 'Elite Pro',
    verificationStatus: 'VERIFIED',
    availabilityType: 'available_now',
    skills: ['Plumbing', 'Concealed Leaks', 'Drain Cleaning', 'Water Heaters', 'Pressure Booster'],
    location: { city: 'Pune', address: 'Baner Road, Pune', coordinates: [73.7898, 18.5590] },
    services: [
      { name: 'Motorized Drain Unblocking Express', slug: 'plumber', price: 499, priceType: 'fixed', description: 'High torque steel snake for stubborn kitchen and bathroom traps.' },
      { name: 'Bathroom Jaguar / Kohler Mixer Repair & Fitting', slug: 'plumber', price: 349, priceType: 'starts_at', description: 'Cartridge replacement and dynamic balance calibration.' },
    ],
    userId: {
      name: 'Pratik Kulkarni',
      avatar: 'https://images.unsplash.com/photo-1522075469751-3a6694fb2f61?auto=format&fit=crop&w=250&q=80',
    },
  },
];
